version: '3.8'

services:
  mongodb:
    image: shehab999/quiz-platform-app:v0.2-db 
    container_name: mongodb
    ports:
      - "27017:27017"  
    volumes:
      - /var/lib/docker/volumes/datavolume2:/data/db  
    networks:
      - app_network

  app:
    image: shehab999/quiz-platform-app:v0.2-app  
    container_name: app
    #working_dir: /app
    volumes:
      - /var/lib/docker/volumes/datavolume2:/app  
    #command: python app.py 
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
    depends_on:
      - mongodb  
    networks:
      - app_network

volumes:
  datavolume: 

networks:
  app_network:  
