version: '3.8'

services:
  mongodb:
    image: shehab999/quiz-platform-app:v0.2-db
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - /var/lib/docker/volumes/datavolume2:/data/db

  app:
    image: shehab999/quiz-platform-app:v0.2-app
    container_name: app
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME="quiz_platform_app"          
      - DB_USERS="users"          
      - DB_QUIZZES="quizzes"      
      - APP_HOST=0.0.0.0        
      - APP_PORT=8000           
    ports:
      - "8000:8000"             
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  datavolume: 

networks:
  app_network:
