version: '3.8'

services:
  mongo:
    build:
      context: ./mongo
    image: quiz-platform-db
    container_name: quiz-mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/docker/test-compose/quiz-platform/volume02:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${DB_CLIENT}

  web:
    build:
      context: ./app
    image: quiz-platform-app
    container_name: quiz-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_CLIENT: ${DB_CLIENT}
      DB_USERS: ${DB_USERS}
      DB_QUIZZES: ${DB_QUIZZES}
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
    depends_on:
      - mongo
    restart: on-failure
